version: "3"

services:

  db:
    image: postgres
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=skillsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password